lint:
	go mod tidy
	go fmt ./...
	go vet ./...
	golangci-lint run ./...

# Run tests with race detection
test-race:
	go test -race -v ./...

# Run full test suite with race detection and coverage
test-full:
	go test -race -cover -coverprofile=coverage.out -v ./...

# Run golangci-lint with race detection enabled
lint-race:
	go mod tidy
	go fmt ./...
	go vet -race ./...
	golangci-lint run ./...
